# Site settings 
title: Peculiar Coding Endeavours
description: 'Software engineer. Algorithm & data structures nut. On my way to mastering AI. Eternal student.'
# url: 'https://tomvanschaijk.github.io'
url: 'https://www.peculiar-coding-endeavours.com'
baseurl: ''
google_analytics: 'UA-118965289-1'
disqus_shortname: 'peculiar-coding-endeavours'

author:
  name: 'Tom van Schaijk'
  email: vanschaijktom@hotmail.com
  github_username:  tomvanschaijk
  linkedin_username:  tom-van-schaijk
  youtube_id: peculiar-coding-endeavours

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate', 'jekyll-feed']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

theme: jekyll-theme-hacker